Repository mahahe-it/helm, pull requests merged in 2024-06, with the labels that each got.

#29 Bump latest chart version on README.md file
  README.md
Labels: Documentation

#24 feat: add ingress class name
  .github/workflows/chart-workflow.yaml
  README.md
  charts/foundry-vtt/Chart.yaml
  charts/foundry-vtt/templates/ingress.yaml
  charts/foundry-vtt/values.yaml
Labels: Enhancement, Minor

#25 fix(foundry-vtt): deployment wasn't adding a volume for data if s3 was disabled
  README.md
  charts/foundry-vtt/Chart.yaml
  charts/foundry-vtt/templates/deployment.yaml
  hugo/content/index.md
Labels: Bugfix
